import os

TEMPLATES = {
    'unit_master.xml': '''<TALLYMESSAGE xmlns:UDF="TallyUDF">
 <UNIT NAME="PKT" RESERVEDNAME="" ACTION="Create">
  <NAME>PKT</NAME>
  <GSTREPUOM>PAC-PACKS</GSTREPUOM>
  <ISSIMPLEUNIT>Yes</ISSIMPLEUNIT>
  <REPORTINGUQCDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <REPORTINGUQCNAME>PAC-PACKS</REPORTINGUQCNAME>
  </REPORTINGUQCDETAILS.LIST>
 </UNIT>
</TALLYMESSAGE>''',

    'stock_group_master.xml': '''<TALLYMESSAGE xmlns:UDF="TallyUDF">
 <STOCKGROUP NAME="Biscuits &amp; Snacks" RESERVEDNAME="" ACTION="Create">
  <NAME>Biscuits &amp; Snacks</NAME>
  <PARENT>Primary</PARENT>
  <ISADDABLE>Yes</ISADDABLE>
 </STOCKGROUP>
</TALLYMESSAGE>''',

    'stock_item_5pct.xml': '''<TALLYMESSAGE xmlns:UDF="TallyUDF">
 <STOCKITEM NAME="BIKAJI CHATPATA SEV 40GM X 192 PKT RS.10/-" RESERVEDNAME="" ACTION="Create">
  <NAME>BIKAJI CHATPATA SEV 40GM X 192 PKT RS.10/-</NAME>
  <PARENT>Biscuits &amp; Snacks</PARENT>
  <BASEUNITS>PKT</BASEUNITS>
  <ADDITIONALUNITS>CASE</ADDITIONALUNITS>
  <DENOMINATOR> 192</DENOMINATOR>
  <CONVERSION> 1</CONVERSION>
  <GSTAPPLICABLE>&#4; Applicable</GSTAPPLICABLE>
  <GSTTYPEOFSUPPLY>Goods</GSTTYPEOFSUPPLY>
  <ISCOSTCENTRESON>No</ISCOSTCENTRESON>
  <ISBATCHWISEON>No</ISBATCHWISEON>
  <ISPERISHABLEON>No</ISPERISHABLEON>
  <OPENINGBALANCE>0</OPENINGBALANCE>
  <GSTDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <CALCULATIONTYPE>On Value</CALCULATIONTYPE>
   <TAXABILITY>Taxable</TAXABILITY>
   <SRCOFGSTDETAILS>Specify Details Here</SRCOFGSTDETAILS>
   <STATEWISEDETAILS.LIST>
    <STATENAME>&#4; Any</STATENAME>
    <RATEDETAILS.LIST>
     <GSTRATEDUTYHEAD>CGST</GSTRATEDUTYHEAD>
     <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
     <GSTRATE> 2.50</GSTRATE>
    </RATEDETAILS.LIST>
    <RATEDETAILS.LIST>
     <GSTRATEDUTYHEAD>SGST/UTGST</GSTRATEDUTYHEAD>
     <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
     <GSTRATE> 2.50</GSTRATE>
    </RATEDETAILS.LIST>
    <RATEDETAILS.LIST>
     <GSTRATEDUTYHEAD>IGST</GSTRATEDUTYHEAD>
     <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
     <GSTRATE> 5.00</GSTRATE>
    </RATEDETAILS.LIST>
   </STATEWISEDETAILS.LIST>
  </GSTDETAILS.LIST>
  <HSNDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <HSNCODE>21069099</HSNCODE>
   <HSN>SEV BHUJIA</HSN>
   <SRCOFHSNDETAILS>Specify Details Here</SRCOFHSNDETAILS>
  </HSNDETAILS.LIST>
 </STOCKITEM>
</TALLYMESSAGE>''',

    'stock_item_18pct.xml': '''<TALLYMESSAGE xmlns:UDF="TallyUDF">
 <STOCKITEM NAME="INDUSTRIAL FASTENER 10MM" RESERVEDNAME="" ACTION="Create">
  <NAME>INDUSTRIAL FASTENER 10MM</NAME>
  <PARENT>Hardware</PARENT>
  <BASEUNITS>PCS</BASEUNITS>
  <GSTAPPLICABLE>&#4; Applicable</GSTAPPLICABLE>
  <GSTTYPEOFSUPPLY>Goods</GSTTYPEOFSUPPLY>
  <ISCOSTCENTRESON>No</ISCOSTCENTRESON>
  <ISBATCHWISEON>No</ISBATCHWISEON>
  <ISPERISHABLEON>No</ISPERISHABLEON>
  <OPENINGBALANCE>0</OPENINGBALANCE>
  <GSTDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <CALCULATIONTYPE>On Value</CALCULATIONTYPE>
   <TAXABILITY>Taxable</TAXABILITY>
   <SRCOFGSTDETAILS>Specify Details Here</SRCOFGSTDETAILS>
   <STATEWISEDETAILS.LIST>
    <STATENAME>&#4; Any</STATENAME>
    <RATEDETAILS.LIST>
     <GSTRATEDUTYHEAD>CGST</GSTRATEDUTYHEAD>
     <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
     <GSTRATE> 9.00</GSTRATE>
    </RATEDETAILS.LIST>
    <RATEDETAILS.LIST>
     <GSTRATEDUTYHEAD>SGST/UTGST</GSTRATEDUTYHEAD>
     <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
     <GSTRATE> 9.00</GSTRATE>
    </RATEDETAILS.LIST>
    <RATEDETAILS.LIST>
     <GSTRATEDUTYHEAD>IGST</GSTRATEDUTYHEAD>
     <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
     <GSTRATE> 18.00</GSTRATE>
    </RATEDETAILS.LIST>
   </STATEWISEDETAILS.LIST>
  </GSTDETAILS.LIST>
  <HSNDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <HSNCODE>73181500</HSNCODE>
   <SRCOFHSNDETAILS>Specify Details Here</SRCOFHSNDETAILS>
  </HSNDETAILS.LIST>
 </STOCKITEM>
</TALLYMESSAGE>''',

    'stock_item_0pct.xml': '''<TALLYMESSAGE xmlns:UDF="TallyUDF">
 <STOCKITEM NAME="FRESH MILK 500ML POUCH" RESERVEDNAME="" ACTION="Create">
  <NAME>FRESH MILK 500ML POUCH</NAME>
  <PARENT>Dairy Products</PARENT>
  <BASEUNITS>POUCH</BASEUNITS>
  <GSTAPPLICABLE>&#4; Applicable</GSTAPPLICABLE>
  <GSTTYPEOFSUPPLY>Goods</GSTTYPEOFSUPPLY>
  <ISCOSTCENTRESON>No</ISCOSTCENTRESON>
  <ISBATCHWISEON>No</ISBATCHWISEON>
  <ISPERISHABLEON>No</ISPERISHABLEON>
  <OPENINGBALANCE>0</OPENINGBALANCE>
  <GSTDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <CALCULATIONTYPE>On Value</CALCULATIONTYPE>
   <TAXABILITY>Nil Rated</TAXABILITY>
   <SRCOFGSTDETAILS>Specify Details Here</SRCOFGSTDETAILS>
   <STATEWISEDETAILS.LIST>
    <STATENAME>&#4; Any</STATENAME>
    <RATEDETAILS.LIST>
     <GSTRATEDUTYHEAD>CGST</GSTRATEDUTYHEAD>
     <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
     <GSTRATE> 0.00</GSTRATE>
    </RATEDETAILS.LIST>
    <RATEDETAILS.LIST>
     <GSTRATEDUTYHEAD>SGST/UTGST</GSTRATEDUTYHEAD>
     <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
     <GSTRATE> 0.00</GSTRATE>
    </RATEDETAILS.LIST>
    <RATEDETAILS.LIST>
     <GSTRATEDUTYHEAD>IGST</GSTRATEDUTYHEAD>
     <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
     <GSTRATE> 0.00</GSTRATE>
    </RATEDETAILS.LIST>
   </STATEWISEDETAILS.LIST>
  </GSTDETAILS.LIST>
  <HSNDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <HSNCODE>04012000</HSNCODE>
   <SRCOFHSNDETAILS>Specify Details Here</SRCOFHSNDETAILS>
  </HSNDETAILS.LIST>
 </STOCKITEM>
</TALLYMESSAGE>''',

    'stock_item_no_alt.xml': '''<TALLYMESSAGE xmlns:UDF="TallyUDF">
 <STOCKITEM NAME="PLAIN CEMENT BAG" RESERVEDNAME="" ACTION="Create">
  <NAME>PLAIN CEMENT BAG</NAME>
  <PARENT>Primary</PARENT>
  <BASEUNITS>BAG</BASEUNITS>
  <GSTAPPLICABLE>&#4; Applicable</GSTAPPLICABLE>
  <GSTTYPEOFSUPPLY>Goods</GSTTYPEOFSUPPLY>
  <ISCOSTCENTRESON>No</ISCOSTCENTRESON>
  <ISBATCHWISEON>No</ISBATCHWISEON>
  <ISPERISHABLEON>No</ISPERISHABLEON>
  <OPENINGBALANCE>0</OPENINGBALANCE>
  <GSTDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <CALCULATIONTYPE>On Value</CALCULATIONTYPE>
   <TAXABILITY>Taxable</TAXABILITY>
   <SRCOFGSTDETAILS>Specify Details Here</SRCOFGSTDETAILS>
   <STATEWISEDETAILS.LIST>
    <STATENAME>&#4; Any</STATENAME>
    <RATEDETAILS.LIST>
     <GSTRATEDUTYHEAD>CGST</GSTRATEDUTYHEAD>
     <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
     <GSTRATE> 14.00</GSTRATE>
    </RATEDETAILS.LIST>
    <RATEDETAILS.LIST>
     <GSTRATEDUTYHEAD>SGST/UTGST</GSTRATEDUTYHEAD>
     <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
     <GSTRATE> 14.00</GSTRATE>
    </RATEDETAILS.LIST>
    <RATEDETAILS.LIST>
     <GSTRATEDUTYHEAD>IGST</GSTRATEDUTYHEAD>
     <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
     <GSTRATE> 28.00</GSTRATE>
    </RATEDETAILS.LIST>
   </STATEWISEDETAILS.LIST>
  </GSTDETAILS.LIST>
  <HSNDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <HSNCODE>25232900</HSNCODE>
   <SRCOFHSNDETAILS>Specify Details Here</SRCOFHSNDETAILS>
  </HSNDETAILS.LIST>
 </STOCKITEM>
</TALLYMESSAGE>''',

    'ledger_regular_creditor.xml': '''<TALLYMESSAGE xmlns:UDF="TALLYUDF">
 <LEDGER NAME="AMAR NATH HARISH CHAND" RESERVEDNAME="" ACTION="Create">
  <NAME>AMAR NATH HARISH CHAND</NAME>
  <PARENT>Sundry Creditors</PARENT>
  <COUNTRYOFRESIDENCE>India</COUNTRYOFRESIDENCE>
  <LEDGERCOUNTRYISDCODE>+91</LEDGERCOUNTRYISDCODE>
  <LEDSTATENAME>Himachal Pradesh</LEDSTATENAME>
  <INCOMETAXNUMBER>AAWFA9436E</INCOMETAXNUMBER>
  <PARTYGSTIN>02AAWFA9436E1ZC</PARTYGSTIN>
  <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
  <ADDRESS.LIST TYPE="String">
   <ADDRESS>MAIN BAZAR KANGRA HIMACHAL PRADESH</ADDRESS>
  </ADDRESS.LIST>
  <PINCODE>176001</PINCODE>
  <LEDGSTREGDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
   <STATE>Himachal Pradesh</STATE>
   <PLACEOFSUPPLY>Himachal Pradesh</PLACEOFSUPPLY>
   <GSTIN>02AAWFA9436E1ZC</GSTIN>
   <ISOTHTERRITORYASSESSEE>No</ISOTHTERRITORYASSESSEE>
  </LEDGSTREGDETAILS.LIST>
  <LEDMAILINGDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <MAILINGNAME>AMAR NATH HARISH CHAND</MAILINGNAME>
   <STATE>Himachal Pradesh</STATE>
   <COUNTRY>India</COUNTRY>
   <PINCODE>176001</PINCODE>
   <ADDRESS.LIST TYPE="String">
    <ADDRESS>MAIN BAZAR KANGRA HIMACHAL PRADESH</ADDRESS>
   </ADDRESS.LIST>
  </LEDMAILINGDETAILS.LIST>
 </LEDGER>
</TALLYMESSAGE>''',

    'ledger_regular_debtor.xml': '''<TALLYMESSAGE xmlns:UDF="TALLYUDF">
 <LEDGER NAME="SHIVA TRADERS" RESERVEDNAME="" ACTION="Create">
  <NAME>SHIVA TRADERS</NAME>
  <PARENT>Sundry Debtors</PARENT>
  <COUNTRYOFRESIDENCE>India</COUNTRYOFRESIDENCE>
  <LEDGERCOUNTRYISDCODE>+91</LEDGERCOUNTRYISDCODE>
  <LEDSTATENAME>Himachal Pradesh</LEDSTATENAME>
  <INCOMETAXNUMBER>AABCS1429B</INCOMETAXNUMBER>
  <PARTYGSTIN>02AABCS1429B1Z1</PARTYGSTIN>
  <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
  <ADDRESS.LIST TYPE="String">
   <ADDRESS>STATION ROAD DHARAMSHALA</ADDRESS>
  </ADDRESS.LIST>
  <PINCODE>176215</PINCODE>
  <LEDGSTREGDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
   <STATE>Himachal Pradesh</STATE>
   <PLACEOFSUPPLY>Himachal Pradesh</PLACEOFSUPPLY>
   <GSTIN>02AABCS1429B1Z1</GSTIN>
   <ISOTHTERRITORYASSESSEE>No</ISOTHTERRITORYASSESSEE>
  </LEDGSTREGDETAILS.LIST>
  <LEDMAILINGDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <MAILINGNAME>SHIVA TRADERS</MAILINGNAME>
   <STATE>Himachal Pradesh</STATE>
   <COUNTRY>India</COUNTRY>
   <PINCODE>176215</PINCODE>
   <ADDRESS.LIST TYPE="String">
    <ADDRESS>STATION ROAD DHARAMSHALA</ADDRESS>
   </ADDRESS.LIST>
  </LEDMAILINGDETAILS.LIST>
 </LEDGER>
</TALLYMESSAGE>''',

    'ledger_unregistered.xml': '''<TALLYMESSAGE xmlns:UDF="TALLYUDF">
 <LEDGER NAME="4G DHABA" RESERVEDNAME="" ACTION="Create">
  <NAME>4G DHABA</NAME>
  <PARENT>Sundry Debtors</PARENT>
  <COUNTRYOFRESIDENCE>India</COUNTRYOFRESIDENCE>
  <LEDGERCOUNTRYISDCODE>+91</LEDGERCOUNTRYISDCODE>
  <LEDSTATENAME>Himachal Pradesh</LEDSTATENAME>
  <GSTREGISTRATIONTYPE>Unregistered/Consumer</GSTREGISTRATIONTYPE>
  <ADDRESS.LIST TYPE="String">
   <ADDRESS>SAKRI</ADDRESS>
  </ADDRESS.LIST>
  <PINCODE></PINCODE>
  <LEDGSTREGDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <GSTREGISTRATIONTYPE>Unregistered/Consumer</GSTREGISTRATIONTYPE>
   <STATE>Himachal Pradesh</STATE>
   <PLACEOFSUPPLY>Himachal Pradesh</PLACEOFSUPPLY>
   <ISOTHTERRITORYASSESSEE>No</ISOTHTERRITORYASSESSEE>
  </LEDGSTREGDETAILS.LIST>
  <LEDMAILINGDETAILS.LIST>
   <APPLICABLEFROM>20210401</APPLICABLEFROM>
   <MAILINGNAME>4G DHABA</MAILINGNAME>
   <STATE>Himachal Pradesh</STATE>
   <COUNTRY>India</COUNTRY>
   <PINCODE></PINCODE>
   <ADDRESS.LIST TYPE="String">
    <ADDRESS>SAKRI</ADDRESS>
   </ADDRESS.LIST>
  </LEDMAILINGDETAILS.LIST>
 </LEDGER>
</TALLYMESSAGE>'''
}

dirs = [
    'd:/KANGRA HUB SALES PURCHASE/fixtures/tally-templates',
    'D:/KANGRA HUB FREE TALLY XML/fixtures/tally-templates',
    'backend/fixtures/tally-templates'
]

if __name__ == '__main__':
    for d in dirs:
        os.makedirs(d, exist_ok=True)
        for fname, content in TEMPLATES.items():
            p = os.path.join(d, fname)
            with open(p, 'w', encoding='utf-8') as f:
                f.write(content.strip() + '\n')
    print('All templates written successfully to all locations.')
